CREATE TABLE IF NOT EXISTS `product_sku` (
    `id` bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    `spu_id` bigint NOT NULL COMMENT 'spu编号',
    `name` varchar(128) NOT NULL DEFAULT '' COMMENT 'SKU 名称',
    `properties` varchar(512)  DEFAULT NULL COMMENT '属性数组，JSON 格式',
    `price` int NOT NULL DEFAULT '-1' COMMENT '商品价格，单位：分',
    `market_price` int DEFAULT NULL COMMENT '市场价，单位：分',
    `cost_price` int NOT NULL DEFAULT '-1' COMMENT '成本价，单位： 分',
    `bar_code` varchar(64)  DEFAULT NULL COMMENT 'SKU 的条形码',
    `pic_url` varchar(256)  NOT NULL COMMENT '图片地址',
    `stock` int DEFAULT NULL COMMENT '库存',
    `weight` double DEFAULT NULL COMMENT '商品重量，单位：kg 千克',
    `volume` double DEFAULT NULL COMMENT '商品体积，单位：m^3 平米',
    `first_brokerage_price` int DEFAULT NULL COMMENT '一级分销的佣金，单位：分',
    `second_brokerage_price` int DEFAULT NULL COMMENT '二级分销的佣金，单位：分',
    `sales_count` int DEFAULT NULL COMMENT '商品销量',
    `status` tinyint NOT NULL DEFAULT '0' COMMENT 'SKU 状态',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint not null default  '0',
    PRIMARY KEY("id")
) COMMENT '商品sku';

CREATE TABLE IF NOT EXISTS `product_spu` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '商品 SPU 编号，自增',
    `name` varchar(128) NOT NULL COMMENT '商品名称',
    `keyword` varchar(256) NOT NULL COMMENT '关键字',
    `introduction` varchar(256) NOT NULL COMMENT '商品简介',
    `description` text NOT NULL COMMENT '商品详情',
    `bar_code` varchar(64) NOT NULL COMMENT '条形码',
    `biz_scene` varchar(32) NOT NULL DEFAULT 'NORMAL' COMMENT '业务场景',
    `brand_id` int DEFAULT NULL COMMENT '商品品牌编号',
    `pic_url` varchar(256) NOT NULL COMMENT '商品封面图',
    `slider_pic_urls` varchar(2000)  DEFAULT '' COMMENT '商品轮播图地址\n 数组，以逗号分隔\n 最多上传15张',
    `video_url` varchar(256) DEFAULT NULL COMMENT '商品视频',
    `unit` tinyint NOT NULL COMMENT '单位',
    `sort` int NOT NULL DEFAULT '0' COMMENT '排序字段',
    `status` tinyint NOT NULL COMMENT '商品状态: 0 上架（开启） 1 下架（禁用）-1 回收',
    `spec_type` bit(1) NOT NULL COMMENT '规格类型：0 单规格 1 多规格',
    `price` int NOT NULL DEFAULT '-1' COMMENT '商品价格，单位使用：分',
    `market_price` int NOT NULL COMMENT '市场价，单位使用：分',
    `cost_price` int NOT NULL DEFAULT '-1' COMMENT '成本价，单位： 分',
    `stock` int NOT NULL DEFAULT '0' COMMENT '库存',
    `delivery_types` varchar(255) DEFAULT NULL COMMENT '配送方式数组',
    `delivery_template_id` bigint DEFAULT NULL COMMENT '物流配置模板编号',
    `recommend_hot` bit(1) NOT NULL COMMENT '是否热卖推荐: 0 默认 1 热卖',
    `recommend_benefit` bit(1) NOT NULL COMMENT '是否优惠推荐: 0 默认 1 优选',
    `recommend_best` bit(1) NOT NULL COMMENT '是否精品推荐: 0 默认 1 精品',
    `recommend_new` bit(1) NOT NULL COMMENT '是否新品推荐: 0 默认 1 新品',
    `recommend_good` bit(1) NOT NULL COMMENT '是否优品推荐',
    `give_integral` int NOT NULL COMMENT '赠送积分',
    `give_coupon_template_ids` varchar(512)  DEFAULT '' COMMENT '赠送的优惠劵编号的数组',
    `sub_commission_type` bit(1) NOT NULL COMMENT '分销类型',
    `activity_orders` varchar(16) NOT NULL DEFAULT '' COMMENT '活动显示排序0=默认, 1=秒杀，2=砍价，3=拼团',
    `sales_count` int DEFAULT '0' COMMENT '商品销量',
    `virtual_sales_count` int DEFAULT '0' COMMENT '虚拟销量',
    `browse_count` int DEFAULT '0' COMMENT '商品点击量',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint not null default  '0',
    PRIMARY KEY("id")
) COMMENT '商品spu';

CREATE TABLE IF NOT EXISTS `product_spu_category_rel` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '关系编号',
    `spu_id` bigint NOT NULL COMMENT '商品 SPU 编号',
    `category_id` bigint NOT NULL COMMENT '商品分类编号',
    `sort` int NOT NULL DEFAULT '0' COMMENT '排序',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint not null default  '0',
    PRIMARY KEY("id")
) COMMENT '商品 SPU 分类关系';

CREATE TABLE IF NOT EXISTS `product_category` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '分类编号',
    `parent_id` bigint NOT NULL COMMENT '父分类编号',
    `name` varchar(255) NOT NULL COMMENT '分类名称',
    `pic_url` varchar(255) NOT NULL COMMENT '移动端分类图',
    `big_pic_url` varchar(255) DEFAULT NULL COMMENT 'PC 端分类图',
    `sort` int DEFAULT '0' COMMENT '分类排序',
    `status` tinyint NOT NULL COMMENT '开启状态',
    `biz_scene` varchar(32) NOT NULL DEFAULT 'NORMAL' COMMENT '业务场景',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint not null default  '0',
    PRIMARY KEY("id")
) COMMENT '商品分类';

CREATE TABLE IF NOT EXISTS `product_brand` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '品牌编号',
    `name` varchar(255) NOT NULL COMMENT '品牌名称',
    `pic_url` varchar(255) NOT NULL COMMENT '品牌图片',
    `sort` int DEFAULT '0' COMMENT '品牌排序',
    `description` varchar(1024) DEFAULT NULL COMMENT '品牌描述',
    `status` tinyint NOT NULL COMMENT '状态',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint not null default  '0',
    PRIMARY KEY("id")
) COMMENT '商品品牌';

CREATE TABLE IF NOT EXISTS `product_publisher` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '出版社编号',
    `name` varchar(255) NOT NULL COMMENT '出版社名称',
    `sort` int NOT NULL DEFAULT '0' COMMENT '排序',
    `status` tinyint NOT NULL DEFAULT '0' COMMENT '状态',
    `remark` varchar(255) DEFAULT NULL COMMENT '备注',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint not null default  '0',
    PRIMARY KEY("id")
) COMMENT '出版社';

CREATE TABLE IF NOT EXISTS `product_publication_type` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '刊物类型编号',
    `name` varchar(255) NOT NULL COMMENT '刊物类型名称',
    `identifier_rule` varchar(64) NOT NULL DEFAULT 'NONE' COMMENT '标识规则',
    `sort` int NOT NULL DEFAULT '0' COMMENT '排序',
    `status` tinyint NOT NULL DEFAULT '0' COMMENT '状态',
    `remark` varchar(255) DEFAULT NULL COMMENT '备注',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint not null default  '0',
    PRIMARY KEY("id")
) COMMENT '刊物类型';

CREATE TABLE IF NOT EXISTS `product_publication_spu_ext` (
    `spu_id` bigint NOT NULL COMMENT 'SPU 编号',
    `publisher_id` bigint NOT NULL COMMENT '出版社编号',
    `publication_type_id` bigint NOT NULL COMMENT '刊物类型编号',
    `issue_mode` varchar(32) NOT NULL DEFAULT 'SINGLE' COMMENT '期次模式',
    `issue_cycle` varchar(64) NOT NULL COMMENT '出刊周期',
    `issn` varchar(64) DEFAULT NULL COMMENT 'ISSN',
    `cn_code` varchar(64) DEFAULT NULL COMMENT 'CN 刊号',
    `post_distribution_code` varchar(64) DEFAULT NULL COMMENT '邮发代号',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint not null default  '0',
    PRIMARY KEY("spu_id")
) COMMENT '刊物 SPU 扩展';

CREATE TABLE IF NOT EXISTS `product_publication_sku_ext` (
    `sku_id` bigint NOT NULL COMMENT 'SKU 编号',
    `isbn` varchar(64) DEFAULT NULL COMMENT 'ISBN',
    `remark` varchar(255) DEFAULT NULL COMMENT '备注',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint not null default  '0',
    PRIMARY KEY("sku_id")
) COMMENT '刊物 SKU 扩展';

CREATE TABLE IF NOT EXISTS `product_publication_sku_issue_template` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
    `sku_id` bigint NOT NULL COMMENT 'SKU 编号',
    `issue_no` int NOT NULL COMMENT '期号',
    `issue_name` varchar(128) NOT NULL COMMENT '期次名称',
    `publish_offset_days` int DEFAULT NULL COMMENT '出刊偏移天数',
    `delivery_offset_days` int DEFAULT NULL COMMENT '配送偏移天数',
    `sort` int NOT NULL DEFAULT '0' COMMENT '排序',
    `status` tinyint NOT NULL DEFAULT '0' COMMENT '状态',
    `remark` varchar(255) DEFAULT NULL COMMENT '备注',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    `active_issue_no` int GENERATED ALWAYS AS (CASE WHEN `deleted` = FALSE THEN `issue_no` ELSE NULL END),
    "tenant_id" bigint not null default  '0',
    PRIMARY KEY("id"),
    UNIQUE KEY `uk_product_publication_sku_issue_template_no` (`sku_id`, `active_issue_no`)
) COMMENT '刊物 SKU 默认期次模板';

CREATE TABLE IF NOT EXISTS `product_publication_sku_grade_rel` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
    `sku_id` bigint NOT NULL COMMENT 'SKU 编号',
    `grade_catalog_id` bigint NOT NULL COMMENT '年级目录编号',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint not null default  '0',
    PRIMARY KEY("id"),
    UNIQUE KEY `uk_product_publication_sku_grade` (`sku_id`, `grade_catalog_id`),
    KEY `idx_product_publication_grade` (`grade_catalog_id`)
) COMMENT '刊物 SKU 适用年级';

CREATE TABLE IF NOT EXISTS `product_property` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
    `name` varchar(64) DEFAULT NULL COMMENT '规格名称',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint not null default  '0',
    `remark` varchar(255) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY("id")
) COMMENT '规格名称';

CREATE TABLE IF NOT EXISTS `product_property_value` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
    `property_id` bigint DEFAULT NULL COMMENT '规格键id',
    `name` varchar(128) DEFAULT NULL COMMENT '规格值名字',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint not null default  '0',
    `remark` varchar(255) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY("id")
) COMMENT '规格值';

CREATE TABLE IF NOT EXISTS `product_comment` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '评论编号，主键自增',
    `spu_id` bigint DEFAULT NULL COMMENT '商品 SPU 编号',
    `sku_id` bigint DEFAULT NULL COMMENT '商品 SKU 编号',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint not null default  '0',
    PRIMARY KEY("id")
) COMMENT '商品评论';
