SET NAMES utf8mb4;

-- Publication fixture data for subscription full-chain verification.
-- The script is repeatable and only cleans rows generated by creator/name/code prefixes below.

DROP TEMPORARY TABLE IF EXISTS tmp_sub_fixture_spu_ids;
CREATE TEMPORARY TABLE tmp_sub_fixture_spu_ids AS
SELECT id
FROM product_spu
WHERE creator = 'codex-publication-fixture'
   OR name LIKE 'SUB_FIX_PUB_%';

DROP TEMPORARY TABLE IF EXISTS tmp_sub_fixture_sku_ids;
CREATE TEMPORARY TABLE tmp_sub_fixture_sku_ids AS
SELECT id
FROM product_sku
WHERE spu_id IN (SELECT id FROM tmp_sub_fixture_spu_ids)
   OR creator = 'codex-publication-fixture';

DROP TEMPORARY TABLE IF EXISTS tmp_sub_fixture_window_spu_ids;
CREATE TEMPORARY TABLE tmp_sub_fixture_window_spu_ids AS
SELECT id
FROM sub_window_spu
WHERE product_spu_id IN (SELECT id FROM tmp_sub_fixture_spu_ids)
   OR creator = 'codex-subscription-smoke';

DELETE FROM sub_window_sku
WHERE window_spu_id IN (SELECT id FROM tmp_sub_fixture_window_spu_ids)
   OR product_sku_id IN (SELECT id FROM tmp_sub_fixture_sku_ids);

DELETE FROM sub_window_spu_rule
WHERE window_spu_id IN (SELECT id FROM tmp_sub_fixture_window_spu_ids);

DELETE FROM sub_window_spu_grade
WHERE window_spu_id IN (SELECT id FROM tmp_sub_fixture_window_spu_ids);

DELETE FROM sub_window_spu
WHERE id IN (SELECT id FROM tmp_sub_fixture_window_spu_ids);

DELETE FROM product_sku_publication
WHERE product_sku_id IN (SELECT id FROM tmp_sub_fixture_sku_ids);

DELETE FROM product_sku
WHERE id IN (SELECT id FROM tmp_sub_fixture_sku_ids);

DELETE FROM product_spu_grade
WHERE product_spu_id IN (SELECT id FROM tmp_sub_fixture_spu_ids);

DELETE FROM product_spu_publication
WHERE product_spu_id IN (SELECT id FROM tmp_sub_fixture_spu_ids);

DELETE FROM product_spu
WHERE id IN (SELECT id FROM tmp_sub_fixture_spu_ids);

DROP TEMPORARY TABLE IF EXISTS tmp_sub_fixture_title_ids;
CREATE TEMPORARY TABLE tmp_sub_fixture_title_ids AS
SELECT id
FROM product_publication_title
WHERE code LIKE 'SUB_FIX_TITLE_%'
   OR creator = 'codex-publication-fixture';

DELETE FROM product_publication_title_identifier
WHERE publication_title_id IN (SELECT id FROM tmp_sub_fixture_title_ids);

DELETE FROM product_publication_title
WHERE id IN (SELECT id FROM tmp_sub_fixture_title_ids);

DELETE FROM product_publication_publisher
WHERE code LIKE 'SUB_FIX_PUBR_%'
   OR creator = 'codex-publication-fixture';

DROP TEMPORARY TABLE IF EXISTS tmp_sub_fixture_num;
CREATE TEMPORARY TABLE tmp_sub_fixture_num AS
WITH RECURSIVE seq(n) AS (
    SELECT 1
    UNION ALL
    SELECT n + 1 FROM seq WHERE n < 120
)
SELECT n FROM seq;

DROP TEMPORARY TABLE IF EXISTS tmp_sub_fixture_grade;
CREATE TEMPORARY TABLE tmp_sub_fixture_grade (
    grade_catalog_id BIGINT NOT NULL PRIMARY KEY,
    grade_code VARCHAR(8) NOT NULL,
    grade_name VARCHAR(16) NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

INSERT INTO tmp_sub_fixture_grade (grade_catalog_id, grade_code, grade_name) VALUES
    (1, 'K1', '小班'),
    (2, 'K2', '中班'),
    (3, 'K3', '大班'),
    (4, 'P1', '一年级'),
    (5, 'P2', '二年级'),
    (6, 'P3', '三年级'),
    (7, 'P4', '四年级'),
    (8, 'P5', '五年级'),
    (9, 'P6', '六年级'),
    (10, 'M1', '初一'),
    (11, 'M2', '初二'),
    (12, 'M3', '初三');

DROP TEMPORARY TABLE IF EXISTS tmp_sub_fixture_type;
CREATE TEMPORARY TABLE tmp_sub_fixture_type (
    code VARCHAR(64) NOT NULL PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    identifier_rule VARCHAR(64) NOT NULL,
    sort_no INT NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

INSERT INTO tmp_sub_fixture_type (code, name, identifier_rule, sort_no) VALUES
    ('BOOK', '书本', 'SKU_ISBN_REQUIRED', 1),
    ('PERIODICAL', '期刊', 'TITLE_PERIODICAL_IDENTIFIER_REQUIRED', 2),
    ('NEWSPAPER', '报纸', 'TITLE_PERIODICAL_IDENTIFIER_REQUIRED', 3),
    ('PACKAGE', '套装', 'NONE', 4);

INSERT INTO product_publication_type (
    code, name, identifier_rule, sort, status, remark, creator, updater, deleted, tenant_id
)
SELECT t.code, t.name, t.identifier_rule, 9000 + t.sort_no, 0, 'subscription publication fixture dependency',
       'codex-publication-fixture', 'codex-publication-fixture', b'0', 1
FROM tmp_sub_fixture_type t
WHERE NOT EXISTS (
    SELECT 1 FROM product_publication_type existing
    WHERE existing.code = t.code AND existing.deleted = b'0'
);

INSERT INTO product_publication_publisher (
    code, name, sort, status, remark, creator, updater, deleted, tenant_id
)
SELECT
    CONCAT('SUB_FIX_PUBR_', LPAD(n, 2, '0')),
    CONCAT('订刊测试出版社', n),
    9000 + n,
    0,
    'subscription full-chain fixture',
    'codex-publication-fixture',
    'codex-publication-fixture',
    b'0',
    1
FROM tmp_sub_fixture_num
WHERE n <= 4;

DROP TEMPORARY TABLE IF EXISTS tmp_sub_fixture_title_plan;
CREATE TEMPORARY TABLE tmp_sub_fixture_title_plan (
    title_seq INT NOT NULL PRIMARY KEY,
    title_code VARCHAR(64) NOT NULL,
    title_name VARCHAR(128) NOT NULL,
    type_code VARCHAR(64) NOT NULL,
    publisher_code VARCHAR(64) NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

INSERT INTO tmp_sub_fixture_title_plan (title_seq, title_code, title_name, type_code, publisher_code)
SELECT
    n AS title_seq,
    CONCAT('SUB_FIX_TITLE_', LPAD(n, 2, '0')) AS title_code,
    CONCAT('订刊测试刊物主档', LPAD(n, 2, '0')) AS title_name,
    CASE MOD(n - 1, 4)
        WHEN 0 THEN 'BOOK'
        WHEN 1 THEN 'PERIODICAL'
        WHEN 2 THEN 'NEWSPAPER'
        ELSE 'PACKAGE'
    END AS type_code,
    CONCAT('SUB_FIX_PUBR_', LPAD(MOD(n - 1, 4) + 1, 2, '0')) AS publisher_code
FROM tmp_sub_fixture_num
WHERE n <= 24;

INSERT INTO product_publication_title (
    code, name, type_id, publisher_id, issue_cycle, status, remark, creator, updater, deleted, tenant_id
)
SELECT
    p.title_code,
    p.title_name,
    t.id,
    publisher.id,
    CASE p.type_code
        WHEN 'BOOK' THEN 'YEARLY'
        WHEN 'PACKAGE' THEN 'YEARLY'
        WHEN 'NEWSPAPER' THEN 'WEEKLY'
        ELSE 'MONTHLY'
    END,
    0,
    'subscription full-chain fixture',
    'codex-publication-fixture',
    'codex-publication-fixture',
    b'0',
    1
FROM tmp_sub_fixture_title_plan p
JOIN product_publication_type t
  ON t.code = p.type_code AND t.deleted = b'0'
JOIN product_publication_publisher publisher
  ON publisher.code = p.publisher_code AND publisher.deleted = b'0';

INSERT INTO product_publication_title_identifier (
    publication_title_id, issn, cn_code, post_distribution_code, creator, updater, deleted, tenant_id
)
SELECT
    title.id,
    CASE WHEN p.type_code IN ('PERIODICAL', 'NEWSPAPER')
         THEN CONCAT('ISSN-978-', LPAD(p.title_seq, 4, '0')) ELSE '' END,
    CASE WHEN p.type_code IN ('PERIODICAL', 'NEWSPAPER')
         THEN CONCAT('CN32-', LPAD(p.title_seq, 4, '0')) ELSE '' END,
    CASE WHEN p.type_code IN ('PERIODICAL', 'NEWSPAPER')
         THEN CONCAT('POST-', LPAD(p.title_seq, 4, '0')) ELSE '' END,
    'codex-publication-fixture',
    'codex-publication-fixture',
    b'0',
    1
FROM tmp_sub_fixture_title_plan p
JOIN product_publication_title title
  ON title.code = p.title_code AND title.deleted = b'0';

DROP TEMPORARY TABLE IF EXISTS tmp_sub_fixture_category;
CREATE TEMPORARY TABLE tmp_sub_fixture_category AS
SELECT id, ROW_NUMBER() OVER (ORDER BY sort, id) AS category_seq
FROM product_category
WHERE parent_id = 90001
  AND status = 0
  AND deleted = b'0'
  AND id <> 90001;

DROP TEMPORARY TABLE IF EXISTS tmp_sub_fixture_spu_plan;
CREATE TEMPORARY TABLE tmp_sub_fixture_spu_plan (
    seq_no INT NOT NULL PRIMARY KEY,
    product_name VARCHAR(128) NOT NULL,
    plan_type VARCHAR(32) NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

INSERT INTO tmp_sub_fixture_spu_plan (seq_no, product_name, plan_type)
SELECT
    n,
    CONCAT('SUB_FIX_PUB_', LPAD(n, 3, '0'), '_', g.grade_code, '_单年级刊物'),
    'SINGLE'
FROM tmp_sub_fixture_num num
JOIN tmp_sub_fixture_grade g ON g.grade_catalog_id = FLOOR((num.n - 1) / 5) + 1
WHERE num.n BETWEEN 1 AND 60;

DROP TEMPORARY TABLE IF EXISTS tmp_sub_fixture_adj_pair;
CREATE TEMPORARY TABLE tmp_sub_fixture_adj_pair (
    pair_no INT NOT NULL PRIMARY KEY,
    start_grade_id BIGINT NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

INSERT INTO tmp_sub_fixture_adj_pair (pair_no, start_grade_id) VALUES
    (1, 1), (2, 2), (3, 4), (4, 5), (5, 6), (6, 7), (7, 8), (8, 10), (9, 11);

INSERT INTO tmp_sub_fixture_spu_plan (seq_no, product_name, plan_type)
SELECT
    60 + (pair_no - 1) * 3 + variant.n,
    CONCAT('SUB_FIX_PUB_', LPAD(60 + (pair_no - 1) * 3 + variant.n, 3, '0'), '_相邻年级刊物'),
    'ADJACENT'
FROM tmp_sub_fixture_adj_pair
JOIN tmp_sub_fixture_num variant ON variant.n <= 3;

INSERT INTO tmp_sub_fixture_spu_plan (seq_no, product_name, plan_type)
SELECT
    87 + n,
    CONCAT('SUB_FIX_PUB_', LPAD(87 + n, 3, '0'), '_幼儿园共用刊物'),
    'K_STAGE'
FROM tmp_sub_fixture_num
WHERE n <= 6;

INSERT INTO tmp_sub_fixture_spu_plan (seq_no, product_name, plan_type)
SELECT
    93 + n,
    CONCAT('SUB_FIX_PUB_', LPAD(93 + n, 3, '0'), '_小学共用刊物'),
    'P_STAGE'
FROM tmp_sub_fixture_num
WHERE n <= 12;

INSERT INTO tmp_sub_fixture_spu_plan (seq_no, product_name, plan_type)
SELECT
    105 + n,
    CONCAT('SUB_FIX_PUB_', LPAD(105 + n, 3, '0'), '_初中共用刊物'),
    'M_STAGE'
FROM tmp_sub_fixture_num
WHERE n <= 6;

INSERT INTO tmp_sub_fixture_spu_plan (seq_no, product_name, plan_type)
SELECT
    111 + n,
    CONCAT('SUB_FIX_PUB_', LPAD(111 + n, 3, '0'), '_全学段通用刊物'),
    'GLOBAL'
FROM tmp_sub_fixture_num
WHERE n <= 9;

SET @sub_fixture_category_count := (SELECT COUNT(*) FROM tmp_sub_fixture_category);

INSERT INTO product_spu (
    name, keyword, introduction, description, category_id, brand_id, pic_url, slider_pic_urls,
    sort, domain_type, status, spec_type, price, market_price, cost_price, stock, delivery_types,
    delivery_template_id, give_integral, sub_commission_type, sales_count, virtual_sales_count, browse_count,
    creator, updater, deleted, tenant_id
)
SELECT
    plan.product_name,
    CONCAT('订刊测试,', plan.plan_type),
    CONCAT('订刊全链路测试刊物 ', plan.seq_no),
    CONCAT('<p>订刊全链路测试数据，编号 ', plan.seq_no, '</p>'),
    category.id,
    NULL,
    CONCAT('https://static.iocoder.cn/subscription-fixture/pub-', LPAD(plan.seq_no, 3, '0'), '.jpg'),
    CONCAT('[\"https://static.iocoder.cn/subscription-fixture/pub-', LPAD(plan.seq_no, 3, '0'), '.jpg\"]'),
    9000 + plan.seq_no,
    'PUBLICATION',
    1,
    b'1',
    1000 + plan.seq_no * 20 + 100,
    1600 + plan.seq_no * 20 + 100,
    600 + plan.seq_no * 10,
    CASE WHEN plan.seq_no <= 12 THEN 300 ELSE 200 END,
    '1,2',
    NULL,
    0,
    b'0',
    0,
    0,
    0,
    'codex-publication-fixture',
    'codex-publication-fixture',
    b'0',
    1
FROM tmp_sub_fixture_spu_plan plan
JOIN tmp_sub_fixture_category category
  ON category.category_seq = MOD(plan.seq_no - 1, @sub_fixture_category_count) + 1;

DROP TEMPORARY TABLE IF EXISTS tmp_sub_fixture_spu_inserted;
CREATE TEMPORARY TABLE tmp_sub_fixture_spu_inserted AS
SELECT plan.seq_no, spu.id AS product_spu_id, plan.product_name, plan.plan_type
FROM tmp_sub_fixture_spu_plan plan
JOIN product_spu spu
  ON spu.name = plan.product_name
 AND spu.creator = 'codex-publication-fixture'
 AND spu.deleted = b'0';

INSERT INTO product_spu_publication (
    product_spu_id, publication_title_id, remark, creator, updater, deleted, tenant_id
)
SELECT
    inserted.product_spu_id,
    title.id,
    'subscription full-chain fixture',
    'codex-publication-fixture',
    'codex-publication-fixture',
    b'0',
    1
FROM tmp_sub_fixture_spu_inserted inserted
JOIN product_publication_title title
  ON title.code = CONCAT('SUB_FIX_TITLE_', LPAD(MOD(inserted.seq_no - 1, 24) + 1, 2, '0'))
 AND title.deleted = b'0';

DROP TEMPORARY TABLE IF EXISTS tmp_sub_fixture_spu_grade_plan;
CREATE TEMPORARY TABLE tmp_sub_fixture_spu_grade_plan (
    seq_no INT NOT NULL,
    grade_catalog_id BIGINT NOT NULL,
    PRIMARY KEY (seq_no, grade_catalog_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

INSERT INTO tmp_sub_fixture_spu_grade_plan (seq_no, grade_catalog_id)
SELECT n, FLOOR((n - 1) / 5) + 1
FROM tmp_sub_fixture_num
WHERE n BETWEEN 1 AND 60;

INSERT INTO tmp_sub_fixture_spu_grade_plan (seq_no, grade_catalog_id)
SELECT 60 + (pair.pair_no - 1) * 3 + variant.n, pair.start_grade_id
FROM tmp_sub_fixture_adj_pair pair
JOIN tmp_sub_fixture_num variant ON variant.n <= 3;

INSERT INTO tmp_sub_fixture_spu_grade_plan (seq_no, grade_catalog_id)
SELECT 60 + (pair.pair_no - 1) * 3 + variant.n, pair.start_grade_id + 1
FROM tmp_sub_fixture_adj_pair pair
JOIN tmp_sub_fixture_num variant ON variant.n <= 3;

INSERT INTO tmp_sub_fixture_spu_grade_plan (seq_no, grade_catalog_id)
SELECT inserted.seq_no, grade.grade_catalog_id
FROM tmp_sub_fixture_spu_inserted inserted
JOIN tmp_sub_fixture_grade grade ON grade.grade_catalog_id BETWEEN 1 AND 3
WHERE inserted.seq_no BETWEEN 88 AND 93;

INSERT INTO tmp_sub_fixture_spu_grade_plan (seq_no, grade_catalog_id)
SELECT inserted.seq_no, grade.grade_catalog_id
FROM tmp_sub_fixture_spu_inserted inserted
JOIN tmp_sub_fixture_grade grade ON grade.grade_catalog_id BETWEEN 4 AND 9
WHERE inserted.seq_no BETWEEN 94 AND 105;

INSERT INTO tmp_sub_fixture_spu_grade_plan (seq_no, grade_catalog_id)
SELECT inserted.seq_no, grade.grade_catalog_id
FROM tmp_sub_fixture_spu_inserted inserted
JOIN tmp_sub_fixture_grade grade ON grade.grade_catalog_id BETWEEN 10 AND 12
WHERE inserted.seq_no BETWEEN 106 AND 111;

INSERT INTO tmp_sub_fixture_spu_grade_plan (seq_no, grade_catalog_id)
SELECT inserted.seq_no, grade.grade_catalog_id
FROM tmp_sub_fixture_spu_inserted inserted
JOIN tmp_sub_fixture_grade grade
WHERE inserted.seq_no BETWEEN 112 AND 120;

INSERT INTO product_spu_grade (
    product_spu_id, grade_catalog_id, creator, updater, deleted, tenant_id
)
SELECT
    inserted.product_spu_id,
    grade_plan.grade_catalog_id,
    'codex-publication-fixture',
    'codex-publication-fixture',
    b'0',
    1
FROM tmp_sub_fixture_spu_grade_plan grade_plan
JOIN tmp_sub_fixture_spu_inserted inserted ON inserted.seq_no = grade_plan.seq_no;

DROP TEMPORARY TABLE IF EXISTS tmp_sub_fixture_sku_variant;
CREATE TEMPORARY TABLE tmp_sub_fixture_sku_variant (
    sku_no INT NOT NULL PRIMARY KEY,
    volume_label VARCHAR(64) NOT NULL,
    edition_label VARCHAR(64) NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

INSERT INTO tmp_sub_fixture_sku_variant (sku_no, volume_label, edition_label) VALUES
    (1, '上册', '标准版'),
    (2, '下册', '增强版'),
    (3, '活动册', '规则测试版');

INSERT INTO product_sku (
    spu_id, properties, price, market_price, cost_price, bar_code, pic_url, stock, weight, volume,
    first_brokerage_price, second_brokerage_price, sales_count, creator, deleted, tenant_id
)
SELECT
    inserted.product_spu_id,
    CONCAT('[{\"propertyId\":0,\"propertyName\":\"版本\",\"valueId\":', variant.sku_no,
           ',\"valueName\":\"', variant.edition_label, '\"}]'),
    1000 + inserted.seq_no * 20 + variant.sku_no * 100,
    1600 + inserted.seq_no * 20 + variant.sku_no * 100,
    600 + inserted.seq_no * 10 + variant.sku_no * 50,
    CONCAT('SUB-FIX-SKU-', LPAD(inserted.seq_no, 3, '0'), '-', variant.sku_no),
    CONCAT('https://static.iocoder.cn/subscription-fixture/pub-', LPAD(inserted.seq_no, 3, '0'), '-', variant.sku_no, '.jpg'),
    100,
    0,
    0,
    0,
    0,
    0,
    'codex-publication-fixture',
    b'0',
    1
FROM tmp_sub_fixture_spu_inserted inserted
JOIN tmp_sub_fixture_sku_variant variant
  ON variant.sku_no <= CASE WHEN inserted.seq_no <= 12 THEN 3 ELSE 2 END;

INSERT INTO product_sku_publication (
    product_sku_id, volume_label, edition_label, target_period, isbn, remark, creator, updater, deleted, tenant_id
)
SELECT
    sku.id,
    variant.volume_label,
    variant.edition_label,
    CASE
        WHEN variant.volume_label IN ('上', '上册', '上学期') OR variant.volume_label LIKE '%上册%' OR variant.volume_label LIKE '%上学期%' THEN 'FIRST_TERM'
        WHEN variant.volume_label IN ('下', '下册', '下学期') OR variant.volume_label LIKE '%下册%' OR variant.volume_label LIKE '%下学期%' THEN 'SECOND_TERM'
        ELSE 'FULL_YEAR'
    END,
    CASE WHEN type.code = 'BOOK' THEN CONCAT('ISBN-978-7-', LPAD(inserted.seq_no, 4, '0'), '-', variant.sku_no)
         ELSE '' END,
    'subscription full-chain fixture',
    'codex-publication-fixture',
    'codex-publication-fixture',
    b'0',
    1
FROM tmp_sub_fixture_spu_inserted inserted
JOIN tmp_sub_fixture_sku_variant variant
  ON variant.sku_no <= CASE WHEN inserted.seq_no <= 12 THEN 3 ELSE 2 END
JOIN product_sku sku
  ON sku.spu_id = inserted.product_spu_id
 AND sku.bar_code = CONCAT('SUB-FIX-SKU-', LPAD(inserted.seq_no, 3, '0'), '-', variant.sku_no)
 AND sku.deleted = b'0'
JOIN product_spu_publication spu_pub
  ON spu_pub.product_spu_id = inserted.product_spu_id AND spu_pub.deleted = b'0'
JOIN product_publication_title title
  ON title.id = spu_pub.publication_title_id AND title.deleted = b'0'
JOIN product_publication_type type
  ON type.id = title.type_id AND type.deleted = b'0';

SELECT
    COUNT(DISTINCT inserted.product_spu_id) AS fixture_spu_count,
    COUNT(DISTINCT sku.id) AS fixture_sku_count,
    COUNT(DISTINCT grade_plan.grade_catalog_id) AS covered_grade_count
FROM tmp_sub_fixture_spu_inserted inserted
LEFT JOIN product_sku sku ON sku.spu_id = inserted.product_spu_id AND sku.deleted = b'0'
LEFT JOIN tmp_sub_fixture_spu_grade_plan grade_plan ON grade_plan.seq_no = inserted.seq_no;
